name: IPTV Auto Merge
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run merge script
        run: python merge.py

      - name: Commit changes
        run: |
          git config --global user.name "Wang963963"
          git config --global user.email "your_email@example.com"
          git add auto_iptv_wang.m3u
          git commit -m "Update IPTV list" || echo "No changes to commit"
          git push