name: IPTV Auto Merge
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install tools
        run: pip install iptv-checker requests

      - name: Run Script
        run: python merge.py

      - name: Commit & Push
        run: |
          git config --global user.name "Wang963963"
          git config --global user.email "your_email@example.com"
          git add .
          git commit -m "Auto update" || echo "No changes to commit"
          git push